#!/bin/sh

# Run SwiftFormat in lint mode (does not modify files)
if mint run swiftformat . --lint | grep -q 'would be formatted'; then
  echo "\033[0;31mERROR: SwiftFormat found files to reformat. Please run 'mint run swiftformat .' and stage the results before committing.\033[0m"
  exit 1
fi

exit 0 